# clw — CoreLink workspaces CLI. PROPRIETARY: the EULA governs use; the
# binary is publicly downloadable but the source is closed. This formula
# is AUTO-GENERATED by the release pipeline — do not hand-edit.
class Clw < Formula
  desc "CoreLink workspaces CLI"
  homepage "https://github.com/HumanGuardrail/clw-releases"
  version "0.1.10"
  # Closed-source: brew has no SPDX expression for this. tap CI gates on
  # `brew style` only (NOT `brew audit --strict`, which rejects this).
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/HumanGuardrail/clw-releases/releases/download/v0.1.10/clw-0.1.10-aarch64-apple-darwin"
      sha256 "9c6af06386e54b9cf284b604a1604dc310c807051294fb608405dae218312631"
    end
    on_intel do
      url "https://github.com/HumanGuardrail/clw-releases/releases/download/v0.1.10/clw-0.1.10-x86_64-apple-darwin"
      sha256 "ee82f5e7a08cd4fa31bc881040a9ac93563ca950e75c20d1dd74d99fb6f28598"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/HumanGuardrail/clw-releases/releases/download/v0.1.10/clw-0.1.10-aarch64-unknown-linux-gnu"
      sha256 "93bc507b07d9b371a1dbe6c4322f5d0644f5a78b3c2550251bc561365d79028d"
    end
    on_intel do
      url "https://github.com/HumanGuardrail/clw-releases/releases/download/v0.1.10/clw-0.1.10-x86_64-unknown-linux-gnu"
      sha256 "343c251925e55ce11f14fd1d2588a758b490f33f517b6fc1975a4953aef26ad9"
    end
  end

  def install
    bin.install Dir["clw-*"].first => "clw"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clw --version")
  end
end
