# clw — CoreLink workspaces CLI. PROPRIETARY: the EULA governs use; the
# binary is publicly downloadable but the source is closed. This formula
# is AUTO-GENERATED by the release pipeline — do not hand-edit.
class Clw < Formula
  desc "CoreLink workspaces CLI"
  homepage "https://github.com/HumanGuardrail/clw-releases"
  version "0.1.11"
  # Closed-source: brew has no SPDX expression for this. tap CI gates on
  # `brew style` only (NOT `brew audit --strict`, which rejects this).
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/HumanGuardrail/clw-releases/releases/download/v0.1.11/clw-0.1.11-aarch64-apple-darwin"
      sha256 "7426367e1e58b309b0ed4183626e073a82e62a79e5c6620d8d3ddf3937ef056d"
    end
    on_intel do
      url "https://github.com/HumanGuardrail/clw-releases/releases/download/v0.1.11/clw-0.1.11-x86_64-apple-darwin"
      sha256 "c7eea2d8e0aa5ad8ea20346996114d45a8989d65d6e9b865518839a07c657e12"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/HumanGuardrail/clw-releases/releases/download/v0.1.11/clw-0.1.11-aarch64-unknown-linux-gnu"
      sha256 "bc01117f611f162ecf3daa89121fa7537dc2e362b1cac9e074ecfbc99dd270c9"
    end
    on_intel do
      url "https://github.com/HumanGuardrail/clw-releases/releases/download/v0.1.11/clw-0.1.11-x86_64-unknown-linux-gnu"
      sha256 "5020e200b3bff8423c46c33255e91d3c68d3220604708ab2463ffe37ec3a9b8f"
    end
  end

  def install
    bin.install Dir["clw-*"].first => "clw"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clw --version")
  end
end
