# clw — CoreLink workspaces CLI. PROPRIETARY: the EULA governs use; the
# binary is publicly downloadable but the source is closed. This formula
# is AUTO-GENERATED by the release pipeline — do not hand-edit.
class Clw < Formula
  desc "CoreLink workspaces CLI"
  homepage "https://github.com/HumanGuardrail/clw-releases"
  version "0.1.4"
  # Closed-source: brew has no SPDX expression for this. tap CI gates on
  # `brew style` only (NOT `brew audit --strict`, which rejects this).
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/HumanGuardrail/clw-releases/releases/download/v0.1.4/clw-0.1.4-aarch64-apple-darwin"
      sha256 "34eb51cb4f3e8b9ea5a153527bf96533f8b9e4b48001212409d17b9140e772b0"
    end
    on_intel do
      url "https://github.com/HumanGuardrail/clw-releases/releases/download/v0.1.4/clw-0.1.4-x86_64-apple-darwin"
      sha256 "68c9302d5b09b984db395d4d66ad07938417383fa71511aeabac708242444bef"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/HumanGuardrail/clw-releases/releases/download/v0.1.4/clw-0.1.4-aarch64-unknown-linux-gnu"
      sha256 "e136d7ad2d9e39defb2452a5b46b659823e6cddccc1b9944541eccb3ae0bdfde"
    end
    on_intel do
      url "https://github.com/HumanGuardrail/clw-releases/releases/download/v0.1.4/clw-0.1.4-x86_64-unknown-linux-gnu"
      sha256 "9ec443d173c6088978cb73caf7b15983ac7161879b3c5663059fea7a4fdf5d8c"
    end
  end

  def install
    bin.install Dir["clw-*"].first => "clw"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clw --version")
  end
end
